name: Deploy via tmux

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 76.13.243.16
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |            
            tmux has-session -t portfolio 2>/dev/null || tmux new -d -s portfolio-3

            tmux send-keys -t portfolio C-c
            sleep 1
            tmux send-keys -t portfolio "git pull origin main" Enter

            tmux send-keys -t portfolio "python smpppp.py" Enter

            curl -s "https://api.telegram.org/bot7896526546:AAEg81oRSVDI4m1y18XTPgsEiSDg1ouSuFo/sendMessage" \
            -d "chat_id=7474379284" \
            -d "text=✅ Deploy successful on VPS 🚀"